# COMPOSE_BAKE=true docker compose -f compose.yml --env-file .env.production up -d
services:
  client:
    image: client
    container_name: client
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    expose:
      - 3000 # Expose port 3000 cho Nginx
    networks:
      - flashease

  nginx:
    image: nginx:latest
    container_name: nginx
    restart: unless-stopped
    volumes:
      - ../nginx/nginx.conf:/etc/nginx/nginx.conf
      - ../certs/letsencrypt:/etc/letsencrypt
    ports:
      - 80:80 # Export cổng 80 ra ngoài
      - 443:443 # Export cổng 443 nếu dùng HTTPS
    depends_on:
      - client
    networks:
      - flashease

networks:
  flashease:
    external: true
