# COMPOSE_BAKE=true docker compose -f compose.local.yml up --build
services:
  nginx:
    image: nginx:latest
    container_name: nginx
    restart: unless-stopped
    ports:
      - 80:80
    volumes:
      - ./nginx.local.conf:/etc/nginx/nginx.conf
    depends_on:
      - client
    networks:
      - flashease

  client:
    image: client_local
    container_name: client
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile.local
    expose:
      - 3000
    volumes:
      - ./src:/app/src
    networks:
      - flashease

networks:
  flashease:
    external: true
