services:
  client:
    image: flashease_client
    container_name: client
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - 80:3000
      - 443:3000
    networks:
      - flashease

networks:
  flashease:
    driver: bridge
