# docker compose -f compose.yml --env-file .env.local up -d --build
services:
  client:
    image: flashease_client
    container_name: client
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    volumes:
      - ./src:/app/src
    ports:
      - 80:3000
      - 443:3000
    networks:
      - flashease
    command: ["pnpm", "dev"]

networks:
  flashease:
    external: true
