# COMPOSE_BAKE=true docker compose -f compose.yml --env-file .env.development up -d --build
services:
  nginx:
    image: nginx:latest
    container_name: nginx
    restart: unless-stopped
    ports:
      - "80:80" # Chỉ cần port 80 cho dev
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf # Mount file nginx.conf đã sửa
    depends_on:
      - client
    networks:
      - flashease

  client:
    image: client_local
    container_name: client
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    volumes:
      - ./src:/app/src
    networks:
      - flashease
    command: ["pnpm", "dev"]

networks:
  flashease:
    external: true
