FROM node:23-alpine

RUN npm install -g pnpm

WORKDIR /app

RUN chown -R node:node /app

USER node

COPY --chown=node:node package*.json pnpm-lock.yaml ./

RUN pnpm install

COPY --chown=node:node . .

ENV NODE_ENV=development

CMD ["pnpm", "dev"]